# Site settings
name: Alec Scott
description: "An impatient futurist, who loves Computer Science and Space."
url: "https://alecbcs.com"


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  alecbcs
blog_url: "/blog"
email: your-email@example.domain
public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars2.githubusercontent.com/u/19558067"

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
